
# Ação do GitHub para gerar um gráfico de contribuição com uma cobra comendo suas contribuições.
nome : Gerar Snake


# A sequência de execuções neste fluxo de trabalho:
empregos :
  # Este fluxo de trabalho contém um único trabalho chamado "build"
  construir :
    # O tipo de executor no qual o trabalho será executado
    executa em : ubuntu-latest

    # As etapas representam uma sequência de tarefas que serão executadas como parte do trabalho
    passos :
      - nome : Repositório clone
        usos : ações/checkout@v3

      - nome : Gerar os arquivos snake em './dist/'
        usos : Platane/snk@v3
        id : cobra-gif
        com :
          nome_de_usuário_github : ${{ github.repository_owner }}
          saídas : |
           dist/github-contribution-grid-snake.svg?color_snake=azul&color_dots=# ffb3b3,#ff6666,#ff4d4d,#ff3333,#e60000
           dist/github-contribution-grid-snake.gif?color_snake=azul&color_dots=# ffb3b3,#ff6666,#ff4d4d,#ff3333,#e60000
      
        ambiente :
           TOKEN_GITHUB : ${{ segredos.MEU_TOKEN_GITHUB }}
      - nome : Mostrar status da compilação
        executar : git status
      - nome : Envie novos arquivos para o branch de saída
        usos : crazy-max/ghaction-github-pages@v3.1.0
        com :
          target_branch : saída
          build_dir : dist
          commit_message : Atualizar animações de cobra
        ambiente :
          TOKEN_GITHUB : ${{ segredos.MEU_TOKEN_GITHUB }}
