name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: MiguelHelen
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#FFFFFF&color_dots=#222222,#444444,#888888,#CCCCCC

      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
